version: "3.4"

services:
  front:
    environment:
        - CHOKIDAR_USEPOLLING=true
    image: og-front
    container_name: og-front
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - 80:80
    tty: true
    #command: bash -c "npm run start"
    networks:
      - og-net
    working_dir: /usr/src/app/og

networks:
  og-net:
    driver: bridge